/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import modelo.*;

/**
 *
 * @author otjos
 */
public class VentanaPrincipal extends javax.swing.JFrame
{

    private JPopupMenu popuMenu;
    private JMenuItem itemModificar, itemEliminar, itemRemodelar, itemFinRemodelacion, itemSubirNivel, itemBajarNivel;
    private JLabel iconSel = null;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal()
    {
        initComponents();
        txtRuta.setText("");
        tbDatos.setModel(Manipula.actualizarTabla(Var.getM().getR()));
        ManipulaTablas.personalizarTabla(tbDatos, "Dependendencia");

        crearMenuOpc();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        marcoPrincipal = new javax.swing.JPanel();
        marcoArb = new javax.swing.JPanel();
        iconDependencia = new javax.swing.JLabel();
        iconHospital = new javax.swing.JLabel();
        iconPacient = new javax.swing.JLabel();
        iconEspecialidad = new javax.swing.JLabel();
        iconFlechaArb = new javax.swing.JLabel();
        marcoBarraRuta = new javax.swing.JPanel();
        txtRuta = new javax.swing.JTextField();
        iconComp = new javax.swing.JLabel();
        iconDerecha = new javax.swing.JLabel();
        marcoIzq = new javax.swing.JPanel();
        marcoCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(850, 400));

        marcoPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        marcoPrincipal.setMaximumSize(new java.awt.Dimension(1100, 600));
        marcoPrincipal.setMinimumSize(new java.awt.Dimension(850, 400));
        marcoPrincipal.setPreferredSize(new java.awt.Dimension(1100, 600));

        marcoArb.setBackground(java.awt.Color.lightGray);

        iconDependencia.setBackground(null);
        iconDependencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/dep_arb.png"))); // NOI18N
        iconDependencia.setToolTipText("Dependencia");
        iconDependencia.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconDependencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconDependencia.setOpaque(true);
        iconDependencia.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iconDependenciaMouseClicked(evt);
            }
        });

        iconHospital.setBackground(null);
        iconHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/hospital_arb.png"))); // NOI18N
        iconHospital.setToolTipText("Hospital");
        iconHospital.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconHospital.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconHospital.setOpaque(true);
        iconHospital.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iconHospitalMouseClicked(evt);
            }
        });

        iconPacient.setBackground(null);
        iconPacient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/paciente_arb.png"))); // NOI18N
        iconPacient.setToolTipText("Paciente");
        iconPacient.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconPacient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconPacient.setOpaque(true);
        iconPacient.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iconPacientMouseClicked(evt);
            }
        });

        iconEspecialidad.setBackground(null);
        iconEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/est_arb.png"))); // NOI18N
        iconEspecialidad.setToolTipText("Especialidad");
        iconEspecialidad.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEspecialidad.setOpaque(true);
        iconEspecialidad.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iconEspecialidadMouseClicked(evt);
            }
        });

        iconFlechaArb.setBackground(null);
        iconFlechaArb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/flecha-arriba.png"))); // NOI18N
        iconFlechaArb.setToolTipText("Subir");
        iconFlechaArb.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconFlechaArb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconFlechaArb.setOpaque(true);
        iconFlechaArb.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                iconFlechaArbMouseClicked(evt);
            }
        });

        marcoBarraRuta.setBackground(new java.awt.Color(204, 204, 204));

        txtRuta.setEditable(false);
        txtRuta.setBackground(new java.awt.Color(204, 204, 204));
        txtRuta.setColumns(45);
        txtRuta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtRutaActionPerformed(evt);
            }
        });

        iconComp.setBackground(null);
        iconComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/pantalla.png"))); // NOI18N
        iconComp.setBorder(new EmptyBorder(3, 3, 3, 3));
        iconComp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconComp.setOpaque(true);

        iconDerecha.setBackground(null);
        iconDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/derecha.png"))); // NOI18N

        javax.swing.GroupLayout marcoBarraRutaLayout = new javax.swing.GroupLayout(marcoBarraRuta);
        marcoBarraRuta.setLayout(marcoBarraRutaLayout);
        marcoBarraRutaLayout.setHorizontalGroup(
            marcoBarraRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoBarraRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconDerecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        marcoBarraRutaLayout.setVerticalGroup(
            marcoBarraRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoBarraRutaLayout.createSequentialGroup()
                .addGroup(marcoBarraRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconComp)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(marcoBarraRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconDerecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout marcoArbLayout = new javax.swing.GroupLayout(marcoArb);
        marcoArb.setLayout(marcoArbLayout);
        marcoArbLayout.setHorizontalGroup(
            marcoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoArbLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(iconDependencia)
                .addGap(18, 18, 18)
                .addComponent(iconHospital)
                .addGap(18, 18, 18)
                .addComponent(iconEspecialidad)
                .addGap(18, 18, 18)
                .addComponent(iconPacient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconFlechaArb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marcoBarraRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1818, Short.MAX_VALUE))
        );
        marcoArbLayout.setVerticalGroup(
            marcoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marcoArbLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(marcoArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(iconFlechaArb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconPacient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconEspecialidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marcoBarraRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout marcoIzqLayout = new javax.swing.GroupLayout(marcoIzq);
        marcoIzq.setLayout(marcoIzqLayout);
        marcoIzqLayout.setHorizontalGroup(
            marcoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        marcoIzqLayout.setVerticalGroup(
            marcoIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        marcoCentro.setBackground(java.awt.Color.lightGray);

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDatos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tbDatosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                tbDatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        javax.swing.GroupLayout marcoCentroLayout = new javax.swing.GroupLayout(marcoCentro);
        marcoCentro.setLayout(marcoCentroLayout);
        marcoCentroLayout.setHorizontalGroup(
            marcoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        marcoCentroLayout.setVerticalGroup(
            marcoCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout marcoPrincipalLayout = new javax.swing.GroupLayout(marcoPrincipal);
        marcoPrincipal.setLayout(marcoPrincipalLayout);
        marcoPrincipalLayout.setHorizontalGroup(
            marcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoPrincipalLayout.createSequentialGroup()
                .addGroup(marcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcoArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(marcoPrincipalLayout.createSequentialGroup()
                        .addComponent(marcoIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marcoCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );
        marcoPrincipalLayout.setVerticalGroup(
            marcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marcoPrincipalLayout.createSequentialGroup()
                .addComponent(marcoArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(marcoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcoIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marcoCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(marcoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(marcoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtRutaActionPerformed
    {//GEN-HEADEREND:event_txtRutaActionPerformed
        // TODO add your handling code he
    }//GEN-LAST:event_txtRutaActionPerformed

    private void tbDatosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tbDatosMouseClicked
    {//GEN-HEADEREND:event_tbDatosMouseClicked
        if (evt.getClickCount() == 2)
        {
            int fila = tbDatos.getSelectedRow();
            if (fila != -1)
            {
                manejarDbClick(fila);
            }
        }
    }//GEN-LAST:event_tbDatosMouseClicked

    private void iconDependenciaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iconDependenciaMouseClicked
    {//GEN-HEADEREND:event_iconDependenciaMouseClicked
        String ruta = txtRuta.getText();
        VentanaCrearDep d = new VentanaCrearDep(this, rootPaneCheckingEnabled, this, ruta);
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_iconDependenciaMouseClicked

    private void iconHospitalMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iconHospitalMouseClicked
    {//GEN-HEADEREND:event_iconHospitalMouseClicked
        String ruta = txtRuta.getText();
        VentanaCrearHos h = new VentanaCrearHos(this, rootPaneCheckingEnabled, this, ruta);
        h.setLocationRelativeTo(this);
        h.setVisible(true);
    }//GEN-LAST:event_iconHospitalMouseClicked

    private void iconEspecialidadMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iconEspecialidadMouseClicked
    {//GEN-HEADEREND:event_iconEspecialidadMouseClicked
        String ruta = txtRuta.getText();
        VentanaCrearEsp e = new VentanaCrearEsp(this, rootPaneCheckingEnabled, this, ruta);
        e.setLocationRelativeTo(this);
        e.setVisible(true);
    }//GEN-LAST:event_iconEspecialidadMouseClicked

    private void iconPacientMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iconPacientMouseClicked
    {//GEN-HEADEREND:event_iconPacientMouseClicked
        String ruta = txtRuta.getText();
        VentanaCrearPac p = new VentanaCrearPac(this, rootPaneCheckingEnabled, this, ruta);
        p.setLocationRelativeTo(this);
        p.setVisible(true);
    }//GEN-LAST:event_iconPacientMouseClicked

    private void iconFlechaArbMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_iconFlechaArbMouseClicked
    {//GEN-HEADEREND:event_iconFlechaArbMouseClicked
        subir();
    }//GEN-LAST:event_iconFlechaArbMouseClicked

    private void tbDatosMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tbDatosMousePressed
    {//GEN-HEADEREND:event_tbDatosMousePressed
        if (SwingUtilities.isRightMouseButton(evt))
        {
            int fila = tbDatos.rowAtPoint(evt.getPoint());
            tbDatos.setRowSelectionInterval(fila, fila);

            String tipo = obtenerTipo(fila);

            popuMenu.removeAll();

            popuMenu.add(itemEliminar);
            popuMenu.add(itemModificar);

            if ("Hospital".equals(tipo))
            {
                popuMenu.addSeparator();
                popuMenu.add(itemRemodelar);
                popuMenu.add(itemFinRemodelacion);
                popuMenu.add(itemSubirNivel);
                popuMenu.add(itemBajarNivel);
            }
            popuMenu.show(tbDatos, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbDatosMousePressed

    private void crearMenuOpc()
    {
        popuMenu = new JPopupMenu();

        itemEliminar = new JMenuItem("Eliminar");
        itemModificar = new JMenuItem("Modificar");

        itemRemodelar = new JMenuItem("Remodelar");
        itemFinRemodelacion = new JMenuItem("Terminar Remodelacion");
        itemSubirNivel = new JMenuItem("Subir a nivel 3");
        itemBajarNivel = new JMenuItem("Bajar de nivel 3");

        itemEliminar.addActionListener(e -> eliminar());
        itemModificar.addActionListener(e -> modificar());
        itemRemodelar.addActionListener(e -> remodelarHospital());
        itemFinRemodelacion.addActionListener(e -> terminarRemodelacion());
        itemSubirNivel.addActionListener(e -> subirNivelHospital());
        itemBajarNivel.addActionListener(e -> bajarNivelHospital());

    }

    private void mostrarMenu(MouseEvent e, JLabel icon)
    {
        popuMenu.show(e.getComponent(), e.getX(), e.getY());
    }

    private String obtenerTipo(int fila)
    {
        String selDir = tbDatos.getValueAt(tbDatos.getSelectedRow(), 2).toString();
        NodoM seleccionado = Var.getM().busca2(Var.getM().getR(), 0, Manipula.dividirCad(txtRuta.getText() + selDir), selDir);
        if (seleccionado != null && seleccionado.getObj() != null)
        {
            if (seleccionado != null && seleccionado.getObj() instanceof Dependencia)
            {
                return "Dependencia";
            } else if (seleccionado != null && seleccionado.getObj() instanceof Hospital)
            {
                return "Hospital";
            } else if (seleccionado != null && seleccionado.getObj() instanceof Especialidad)
            {
                return "Especialidad";
            } else if (seleccionado != null && seleccionado.getObj() instanceof Paciente)
            {
                return "Paciente";
            }
        }
        return "";
    }

    private void eliminar()
    {

        System.out.println("******************************************eliminar seleccionado *****************************************");
        int fila = tbDatos.getSelectedRow();
        if (fila >= 0)
        {
            System.out.println("*********************************sin eliminar*************************");
            System.out.println(Var.getM().desplegar(Var.getM().getR(), ""));
            String nombre = tbDatos.getValueAt(fila, 2).toString();//elige el dato de la tabla a eliminaer
            System.out.println("seleccionado: " + nombre);
            String rutaTexto = txtRuta.getText();//ruta actual
            System.out.println("ruta: " + rutaTexto);

            //genera un vector de cadenas que incluye el nombre para pasarlo al metodo que ocupa el nombre
            String[] ruta = Manipula.dividirCad(rutaTexto + nombre);
            //genera un vector de cadena para buscar el padre de ese nodo ,solo para imprimir los datos que tiene ABJ
            String[] rutaDato = Manipula.dividirCad(rutaTexto);

            NodoM nodoEliminar = Var.getM().buscarRuta(Var.getM().getR(), rutaDato, 0);
            if (nodoEliminar != null)
            {
                System.out.println("eliminado=" + nodoEliminar.getEt());
                NodoM nodoArb = nodoEliminar.getArriba();
                Manipula.eliminar(ruta);

                if (nodoArb != null)
                {
                    System.out.println("eliminadoARB=" + nodoArb.getEt());
                    if (nodoArb.getAbajo() != null)
                    {
                        Manipula.actualizarYPersonalizar(nodoArb.getAbajo(), tbDatos);
                        //txtRuta.setText(rutaTexto);
                    } else
                    {
                        if (rutaTexto.endsWith("/"))
                        {
                            rutaTexto = rutaTexto.substring(0, rutaTexto.length() - 1);
                        }
                        int ultimoSlash = rutaTexto.lastIndexOf("/");
                        if (ultimoSlash != -1)
                        {
                            rutaTexto = rutaTexto.substring(0, ultimoSlash + 1); // incluir el slash final
                        } else
                        {
                            rutaTexto = ""; // raíz
                        }

                        nodoArb = nodoArb.getArriba();
                        if (nodoArb != null)
                        {
                            Manipula.actualizarYPersonalizar(nodoArb.getAbajo(), tbDatos);
                        } else
                        {
                            Manipula.actualizarYPersonalizar(Var.getM().getR(), tbDatos);
                        }
                        txtRuta.setText(rutaTexto);
                    }
                } else
                {
                    System.out.println("***************nivel mas alto");
                    Manipula.actualizarYPersonalizar(Var.getM().getR(), tbDatos);
                    txtRuta.setText("");
                }
                System.out.println("*********************************DATO ELIMINADO*************************");

                ManipulaArchivos.guardar(Var.getM(), "datos.dat");
                ManipulaArchivos.guardarContador(Datos.getContadorGeneral(), "contador.dat");
                System.out.println(Var.getM().desplegar(Var.getM().getR(), ""));
            } else
            {
                JOptionPane.showMessageDialog(null, "no se encontro el nodo ");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento para eliminar.");
        }
    }

    private void modificar()
    {
        System.out.println("Modificar seleccionado");
        int fila = tbDatos.getSelectedRow();
        if (fila >= 0)
        {
            String seleccionado = tbDatos.getValueAt(fila, 2).toString();
            String rutaTxt = txtRuta.getText();
            System.out.println("Fila seleccionada: " + fila);
            System.out.println("Valor seleccionado: " + seleccionado);
            
            if (!rutaTxt.endsWith("/"))
            {
                rutaTxt+="/";
            }

            String[] ruta = Manipula.dividirCad(rutaTxt);
            NodoM nodoPadre = Var.getM().buscarRuta(Var.getM().getR(), ruta, 0);
            NodoM nodoModificar = Var.getM().buscaAux(nodoPadre, seleccionado);
            System.out.println("*************"+nodoModificar.getEt());
            if (nodoModificar != null)
            {
                Object obj = nodoModificar.getObj();
                if (obj instanceof Datos datos)
                {
                    String clave = datos.getClave();
                    String nombre = datos.getNombre();
                    if (obj instanceof Dependencia dep)
                    {
                        System.out.println("abrinedo vtn mod dep");
                        new VentanaCrearDep(this, rootPaneCheckingEnabled, this, rutaTxt, dep).setVisible(true);
                        
                    } else if (obj instanceof Hospital hos)
                    {
                        new VentanaCrearHos(this, rootPaneCheckingEnabled, this, rutaTxt, hos, nodoModificar).setVisible(true);

                    } else if (obj instanceof Especialidad esp)
                    {
                        new VentanaCrearEsp(this, rootPaneCheckingEnabled, this, rutaTxt, esp, nodoModificar).setVisible(true);

                    } else if (obj instanceof Paciente pac)
                    {
                        new VentanaCrearPac(this, rootPaneCheckingEnabled, this, rutaTxt, pac, nodoModificar).setVisible(true);

                    }
                }
            } else
            {
            }

        } else
        {
        }

    }

    private void remodelarHospital()
    {
        System.out.println("Remodelar hospital seleccionado");

    }

    private void terminarRemodelacion()
    {
        System.out.println("Finalizar remodelacion seleccionado");
    }

    private void subirNivelHospital()
    {
        System.out.println("Subir a nivel 3 seleccionado");
    }

    private void bajarNivelHospital()
    {
        System.out.println("Bajar de nivel 3 seleccionado");
    }

    private void manejarDbClick(int fila)
    {
        String selDir = tbDatos.getValueAt(tbDatos.getSelectedRow(), 2).toString();
        NodoM seleccionado = Var.getM().busca2(Var.getM().getR(), 0, Manipula.dividirCad(txtRuta.getText() + selDir), selDir);
        if (seleccionado != null && seleccionado.getAbajo() != null)
        {
            txtRuta.setText(txtRuta.getText() + selDir + "/");
            NodoM abj = seleccionado.getAbajo();
            Manipula.actualizarYPersonalizar(abj, tbDatos);
        }
    }

    public void actualizarTablaPrincipal()
    {
        String rutaActal = txtRuta.getText();
        String[] ruta = Manipula.dividirCad(rutaActal);
        NodoM nodo = Var.getM().buscarRuta(Var.getM().getR(), ruta, 0);
        DefaultTableModel modelo = Manipula.actualizarTabla(nodo);
        tbDatos.setModel(modelo);
    }

    private void subir()
    {
        if (!txtRuta.getText().isBlank())
        {
            String[] arr = Manipula.dividirCad(txtRuta.getText());
            if (arr.length > 0)
            {
                NodoM anterior = Var.getM().busca2(Var.getM().getR(), 0, arr, arr[arr.length - 1]);
                anterior = (anterior.getArriba() != null) ? anterior.getArriba().getAbajo() : Var.getM().getR();

                String ruta = txtRuta.getText();
                if (ruta.endsWith("/"))
                {
                    ruta = ruta.substring(0, ruta.length() - 1);
                }

                int lastSlash = ruta.lastIndexOf("/");
                if (lastSlash != -1)
                {
                    ruta = ruta.substring(0, lastSlash + 1);
                } else
                {
                    ruta = ""; // Ya estamos en raíz
                }
                txtRuta.setText(ruta);

                DefaultTableModel modelo = Manipula.actualizarTabla(anterior);
                tbDatos.setModel(modelo);

                if (anterior != null)
                {

                    Object obj = anterior.getObj();
                    if (obj instanceof Dependencia)
                    {
                        ManipulaTablas.personalizarTabla(tbDatos, "Dependencia");
                    } else if (obj instanceof Hospital)
                    {
                        ManipulaTablas.personalizarTabla(tbDatos, "Hospital");
                    } else if (obj instanceof Especialidad)
                    {
                        ManipulaTablas.personalizarTabla(tbDatos, "Especialidad");
                    } else if (obj instanceof Paciente)
                    {
                        ManipulaTablas.personalizarTabla(tbDatos, "Paciente");
                    }

                }
            }
        }
    }

    private void ejecutarAccion(String accion)
    {

    }
    /**
     * @param args the command line arguments //
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                new VentanaPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconComp;
    private javax.swing.JLabel iconDependencia;
    private javax.swing.JLabel iconDerecha;
    private javax.swing.JLabel iconEspecialidad;
    private javax.swing.JLabel iconFlechaArb;
    private javax.swing.JLabel iconHospital;
    private javax.swing.JLabel iconPacient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel marcoArb;
    private javax.swing.JPanel marcoBarraRuta;
    private javax.swing.JPanel marcoCentro;
    private javax.swing.JPanel marcoIzq;
    private javax.swing.JPanel marcoPrincipal;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

    public JTable getTbDatos()
    {
        return tbDatos;
    }

    public void setTbDatos(JTable tbDatos)
    {
        this.tbDatos = tbDatos;
    }

    public javax.swing.JTextField getTxtRuta()
    {
        return txtRuta;
    }

    public void setTxtRuta(javax.swing.JTextField txtRuta)
    {
        this.txtRuta = txtRuta;
    }

}
