/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import com.sun.jdi.OpaqueFrameException;
import controlador.Manipula;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.*;
import controlador.*;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author otjos
 */
public class VentanaCrearEsp extends javax.swing.JDialog
{

    /**
     * Creates new form CrearVentanaDep
     */
    private VentanaPrincipal principal;
    private String rutaActual;

    public VentanaCrearEsp(java.awt.Frame parent, boolean modal, VentanaPrincipal principal, String rutaActual)
    {
        super(parent, modal);
        this.principal = principal;
        this.rutaActual = rutaActual;
        initComponents();

        String claveTemporal = String.format("E.%03d", Datos.getContadorGeneral() + 1);
        txtClave.setText(claveTemporal);

        llenarComboDependencias(JCDependencia, Var.getM().getR());
        JCDependencia.addActionListener(e ->
        {
            agregarHospitales(JCDependencia, JCHospital, Var.getM().getR());
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bg = new javax.swing.JPanel();
        bgArb = new javax.swing.JPanel();
        iconPropiedas = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JLabel();
        Clave = new javax.swing.JLabel();
        Clave1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtNumCamas = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bgAbj = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JLabel();
        JCDependencia = new javax.swing.JComboBox<>();
        Clave2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Clave3 = new javax.swing.JLabel();
        Clave4 = new javax.swing.JLabel();
        txtNumMedicos = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        JCHospital = new javax.swing.JComboBox<>();
        Clave5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 250));
        setResizable(false);

        bg.setBackground(java.awt.Color.white);
        bg.setMaximumSize(new java.awt.Dimension(300, 250));
        bg.setMinimumSize(new java.awt.Dimension(300, 250));
        bg.setPreferredSize(new java.awt.Dimension(300, 250));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgArb.setBackground(new java.awt.Color(102, 153, 255));

        iconPropiedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/estetoscopio.png"))); // NOI18N

        txtNombreClase.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtNombreClase.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreClase.setText("ESPECIALIDAD");

        javax.swing.GroupLayout bgArbLayout = new javax.swing.GroupLayout(bgArb);
        bgArb.setLayout(bgArbLayout);
        bgArbLayout.setHorizontalGroup(
            bgArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgArbLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconPropiedas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        bgArbLayout.setVerticalGroup(
            bgArbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconPropiedas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgArbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(bgArb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        Clave.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave.setForeground(new java.awt.Color(51, 51, 51));
        Clave.setText("CLAVE");
        Clave.setToolTipText("");
        bg.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 56, 11));

        Clave1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave1.setForeground(new java.awt.Color(51, 51, 51));
        Clave1.setText("NOMBRE");
        Clave1.setToolTipText("");
        bg.add(Clave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 79, -1));

        txtClave.setEditable(false);
        txtClave.setBackground(java.awt.Color.white);
        txtClave.setColumns(7);
        txtClave.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBorder(null);
        txtClave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtClaveActionPerformed(evt);
            }
        });
        bg.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 71, -1));

        txtNumCamas.setBackground(java.awt.Color.white);
        txtNumCamas.setColumns(45);
        txtNumCamas.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNumCamas.setForeground(new java.awt.Color(102, 102, 102));
        txtNumCamas.setText("Ingresa el numero de camas");
        txtNumCamas.setBorder(null);
        txtNumCamas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumCamas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                txtNumCamasMousePressed(evt);
            }
        });
        txtNumCamas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNumCamasActionPerformed(evt);
            }
        });
        txtNumCamas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNumCamasKeyTyped(evt);
            }
        });
        bg.add(txtNumCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 160, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 57, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, -1));

        bgAbj.setBackground(new java.awt.Color(102, 153, 255));

        btnGuardar.setBackground(new java.awt.Color(102, 153, 255));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setOpaque(true);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                btnGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgAbjLayout = new javax.swing.GroupLayout(bgAbj);
        bgAbj.setLayout(bgAbjLayout);
        bgAbjLayout.setHorizontalGroup(
            bgAbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgAbjLayout.setVerticalGroup(
            bgAbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        bg.add(bgAbj, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 225, 300, -1));

        JCDependencia.setBackground(new java.awt.Color(204, 204, 204));
        JCDependencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCDependencia.setForeground(new java.awt.Color(0, 0, 0));
        JCDependencia.setBorder(null);
        JCDependencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JCDependenciaActionPerformed(evt);
            }
        });
        bg.add(JCDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, 20));

        Clave2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave2.setForeground(new java.awt.Color(51, 51, 51));
        Clave2.setText("DEPENDENCIA");
        Clave2.setToolTipText("");
        bg.add(Clave2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        txtNombre.setBackground(java.awt.Color.white);
        txtNombre.setColumns(45);
        txtNombre.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Ingrese el nombre ");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 183, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 196, -1));

        Clave3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave3.setForeground(new java.awt.Color(51, 51, 51));
        Clave3.setText("CAMAS");
        Clave3.setToolTipText("");
        bg.add(Clave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 79, 20));

        Clave4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave4.setForeground(new java.awt.Color(51, 51, 51));
        Clave4.setText("MEDICOS");
        Clave4.setToolTipText("");
        bg.add(Clave4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 79, 20));

        txtNumMedicos.setBackground(java.awt.Color.white);
        txtNumMedicos.setColumns(45);
        txtNumMedicos.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNumMedicos.setForeground(new java.awt.Color(102, 102, 102));
        txtNumMedicos.setText("Ingresa el numero de medicos");
        txtNumMedicos.setBorder(null);
        txtNumMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumMedicos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                txtNumMedicosMousePressed(evt);
            }
        });
        txtNumMedicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNumMedicosActionPerformed(evt);
            }
        });
        txtNumMedicos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtNumMedicosKeyTyped(evt);
            }
        });
        bg.add(txtNumMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 170, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, -1));

        JCHospital.setBackground(new java.awt.Color(204, 204, 204));
        JCHospital.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCHospital.setForeground(new java.awt.Color(0, 0, 0));
        JCHospital.setBorder(null);
        JCHospital.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JCHospitalActionPerformed(evt);
            }
        });
        bg.add(JCHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 20));

        Clave5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Clave5.setForeground(new java.awt.Color(51, 51, 51));
        Clave5.setText("HOSPITAL");
        Clave5.setToolTipText("");
        bg.add(Clave5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtClaveActionPerformed
    {//GEN-HEADEREND:event_txtClaveActionPerformed

    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtNumCamasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNumCamasActionPerformed
    {//GEN-HEADEREND:event_txtNumCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCamasActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseEntered
    {//GEN-HEADEREND:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(102, 175, 240));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseExited
    {//GEN-HEADEREND:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(102, 153, 255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void txtNumCamasMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNumCamasMousePressed
    {//GEN-HEADEREND:event_txtNumCamasMousePressed
        txtNumCamas.setText("");
        txtNumCamas.setForeground(Color.black);
    }//GEN-LAST:event_txtNumCamasMousePressed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnGuardarMouseClicked
    {//GEN-HEADEREND:event_btnGuardarMouseClicked
        //JOptionPane.showMessageDialog(this, "correcto");
        nuevo();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void JCDependenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JCDependenciaActionPerformed
    {//GEN-HEADEREND:event_JCDependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCDependenciaActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNombreMousePressed
    {//GEN-HEADEREND:event_txtNombreMousePressed
        txtNombre.setText("");
        txtNombre.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNumMedicosMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_txtNumMedicosMousePressed
    {//GEN-HEADEREND:event_txtNumMedicosMousePressed
        txtNumMedicos.setText("");
        txtNumMedicos.setForeground(Color.black);
    }//GEN-LAST:event_txtNumMedicosMousePressed

    private void txtNumMedicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNumMedicosActionPerformed
    {//GEN-HEADEREND:event_txtNumMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumMedicosActionPerformed

    private void JCHospitalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JCHospitalActionPerformed
    {//GEN-HEADEREND:event_JCHospitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCHospitalActionPerformed

    private void txtNumCamasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNumCamasKeyTyped
    {//GEN-HEADEREND:event_txtNumCamasKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b')
        { // solo números
            evt.consume(); // no acepta la tecla
        }
    }//GEN-LAST:event_txtNumCamasKeyTyped

    private void txtNumMedicosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtNumMedicosKeyTyped
    {//GEN-HEADEREND:event_txtNumMedicosKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '\b')
        { // solo números
            evt.consume(); // no acepta la tecla
        }
    }//GEN-LAST:event_txtNumMedicosKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(VentanaCrearDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                VentanaCrearDep dialog = new VentanaCrearDep(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter()
//                {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e)
//                    {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    private void nuevo()
    {
        if (camposValidados())
        {
            String nombre = Manipula.formatoPalabras(txtNombre.getText());

            String nCamas = txtNumCamas.getText().trim();
            String nMedicos = txtNumMedicos.getText().trim();

            if (!Manipula.esEnteroValido(nCamas) || !Manipula.esEnteroValido(nMedicos))
            {
                JOptionPane.showMessageDialog(this, "Ingresa numeros validos");
                return;
            }

            int numCamas = Integer.parseInt(txtNumCamas.getText());
            int numMedicos = Integer.parseInt(txtNumMedicos.getText());

            String dependencia = (String) JCDependencia.getSelectedItem();
            String hospital = (String) JCHospital.getSelectedItem();
            Especialidad e = new Especialidad(numCamas, numMedicos, nombre);

            String[] ruta = new String[3];
            ruta[0] = dependencia;
            ruta[1] = hospital;
            ruta[2] = nombre;
            Manipula.insertar(e, nombre, ruta);

            //NodoM nodo = Var.getM().buscarRuta(Var.getM().getR(), ruta, 0);
            //NodoM nodo = Var.getM().getR();
            NodoM nodo = Var.getM().busca(Var.getM().getR(), ruta[0]);
            NodoM nodoHospital = Var.getM().busca(nodo.getAbajo(), ruta[1]);
            NodoM nodoEspecialidad = Var.getM().busca(nodoHospital.getAbajo(), ruta[2]);

            DefaultTableModel modelo = Manipula.actualizarTabla(nodoEspecialidad);

            System.out.println(Var.getM().desplegar(Var.getM().getR(), ""));

            principal.getTbDatos().setModel(modelo);
            ManipulaTablas.personalizarTabla(principal.getTbDatos(), "Especiaidad");

            ManipulaArchivos.guardar(Var.getM(), "datos.dat");
            ManipulaArchivos.guardarContador(Datos.getContadorGeneral(), "contador.dat");

            VentanaCrearEsp.this.dispose();
            //JOptionPane.showMessageDialog(this, "Dependencia guardada");
        } else
        {
            JOptionPane.showMessageDialog(this, "Completa todos los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean camposValidados()
    {
        String dependencia = (String) JCDependencia.getSelectedItem();
        String hospital = (String) JCHospital.getSelectedItem();

        if (txtNombre.getText().trim().isBlank()
                || txtNumCamas.getText().trim().isBlank()
                || txtNumMedicos.getText().trim().isBlank())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos de texto deben estar llenos");
            return false;
        }

        if (dependencia == null || dependencia.equals("Selecciona..."))
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una dependencia");
            return false;
        }

        if (hospital == null || hospital.equals("Selecciona..."))
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un hospital .");
            return false;
        }

        return true;
    }

    public static void llenarComboDependencias(JComboBox combo, NodoM n)
    {
        combo.removeAllItems();
        combo.addItem("Selecciona...");
        agregarDependencias(combo, n);
    }

    public static void agregarDependencias(JComboBox combo, NodoM n)
    {
        if (n != null)
        {
            NodoM aux = n.getSiguiente();
            do
            {
                if (aux.getObj() instanceof Dependencia)
                {
                    combo.addItem(aux.getEt());
                }
                aux = aux.getSiguiente();
            } while (aux != n.getSiguiente());
        } else
        {
            return;
        }
    }

    public static void agregarHospitales(JComboBox comboDep, JComboBox comboHos, NodoM r)
    {
        String dependencia = (String) comboDep.getSelectedItem();
        comboHos.removeAllItems();
        comboHos.addItem("Selecciona...");
        if (dependencia != null && !dependencia.equals("Selecciona..."))
        {
            NodoM nodoDep = Var.getM().busca(r, dependencia);
            if (nodoDep != null && nodoDep.getAbajo() != null)
            {
                boolean tiene = false;
                NodoM aux = nodoDep.getAbajo().getSiguiente();
                do
                {
                    if (aux.getObj() instanceof Hospital)
                    {
                        comboHos.addItem(aux.getEt());
                        tiene = true;
                    }
                    aux = aux.getSiguiente();
                } while (aux != nodoDep.getAbajo().getSiguiente());
                comboHos.setEnabled(tiene);
            } else
            {
                comboHos.setEnabled(false);
            }
        } else
        {
            comboHos.setEnabled(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Clave1;
    private javax.swing.JLabel Clave2;
    private javax.swing.JLabel Clave3;
    private javax.swing.JLabel Clave4;
    private javax.swing.JLabel Clave5;
    private javax.swing.JComboBox<String> JCDependencia;
    private javax.swing.JComboBox<String> JCHospital;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgAbj;
    private javax.swing.JPanel bgArb;
    private javax.swing.JLabel btnGuardar;
    private javax.swing.JLabel iconPropiedas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtNombreClase;
    private javax.swing.JTextField txtNumCamas;
    private javax.swing.JTextField txtNumMedicos;
    // End of variables declaration//GEN-END:variables
}
